# EIGENVALUE PROBLEMS

1. Eigenvalues
2. Eigenvectors
3. Eigenlines and Eigenspace
4. Applications

In [2]:
import numpy as np
import matplotlib as mp

In [3]:
A = np.array([
    [-2,2,-3],
    [2,1,-6],
    [-1,2,0]
])

print(A)
print(type(A))

[[-2  2 -3]
 [ 2  1 -6]
 [-1  2  0]]
<class 'numpy.ndarray'>


In [4]:
eigvals_A = np.linalg.eigvals(A)
eig_A = np.linalg.eig(A)

print("Result 1:\n {0} \nResult 2:\n{1}" .format(eigvals_A,eig_A))

Result 1:
 [-3.+0.j          1.+2.82842712j  1.-2.82842712j] 
Result 2:
(array([-3.+0.j        ,  1.+2.82842712j,  1.-2.82842712j]), array([[-9.48683298e-01+0.00000000e+00j,  4.08248290e-01+4.15958896e-16j,
         4.08248290e-01-4.15958896e-16j],
       [ 2.78100526e-17+0.00000000e+00j,  8.16496581e-01+0.00000000e+00j,
         8.16496581e-01-0.00000000e+00j],
       [-3.16227766e-01+0.00000000e+00j,  1.36082763e-01-3.84900179e-01j,
         1.36082763e-01+3.84900179e-01j]]))
